// AUTO-GENERATED by scripts/gen-provider-icons.py.
#pragma once
#include "lvgl.h"
#include <string.h>

// A8 silhouette of the provider's CodexBar logo, or NULL.
// Tint via the lv_image's image_recolor style.
const lv_image_dsc_t *provider_icon(const char *id);
