// AUTO-GENERATED by scripts/build/gen-provider-icons.py.
#pragma once
#include "lvgl.h"
#include <stdbool.h>
#include <string.h>

// A8 silhouette or ARGB8888 full-color image, or NULL.
// A8 icons must be tinted via lv_image's image_recolor style;
// ARGB8888 icons carry their own colors (check is_full_color).
const lv_image_dsc_t *provider_icon(const char *id);

// Compact icon variant for the summary provider rows.
const lv_image_dsc_t *provider_summary_icon(const char *id);

// Background watermark variant (large, blurred) for per-provider pages.
const lv_image_dsc_t *provider_background_icon(const char *id);

// Returns true if the icon for `id` is ARGB8888 (full color).
// When true, do NOT apply image_recolor to the icon.
bool provider_icon_is_full_color(const char *id);
