#!/usr/bin/env python3
# gen-provider-icons.py — rasterize the vendored CodexBar provider logo SVGs
# (scripts/assets/codexbar-logos/, sourced from github.com/steipete/CodexBar
# docs/logos/) into small LVGL **A8** images and emit
# firmware/main/provider_icons.{c,h}.
#
# A8 = one alpha byte per pixel (shape coverage only, no color). The firmware
# tints each icon with the provider's CodexBar accent via the LVGL
# image_recolor style, so this is color-agnostic by design and works on the
# dark UI regardless of the logo's own colors.
#
# Deps: rsvg-convert (brew install librsvg) + Pillow. Re-run after changing
# the vendored SVGs or ICON_PX; the generated .c is committed (build input,
# like the LVGL fonts).
#
#   python3 scripts/gen-provider-icons.py
import os, subprocess, sys, tempfile
from PIL import Image

ICON_PX = 32
HERE = os.path.dirname(os.path.abspath(__file__))
SVG_DIR = os.path.join(HERE, "assets", "codexbar-logos")
OUT_C = os.path.join(HERE, "..", "firmware", "main", "provider_icons.c")
OUT_H = os.path.join(HERE, "..", "firmware", "main", "provider_icons.h")

# provider id (UsageProvider raw value == payload `id`) -> svg basename.
# Several ids legitimately share one logo.
ID_TO_SVG = {
    "claude": "claude", "codex": "codex", "openai": "codex", "pi": "pi",
    "cursor": "cursor", "openrouter": "openrouter",
    "opencode": "opencode", "opencodego": "opencode",
    "ollama": "ollama", "gemini": "gemini", "copilot": "copilot",
    "alibaba": "alibaba", "amp": "amp", "antigravity": "antigravity",
    "augment": "augment", "deepseek": "deepseek", "elevenlabs": "elevenlabs",
    "factory": "droid", "jetbrains": "jetbrains-ai", "kilo": "kilo",
    "kimi": "kimi", "kimik2": "kimi-k2", "kiro": "kiro",
    "minimax": "minimax", "mistral": "mistral", "perplexity": "perplexity",
    "vertexai": "vertex-ai", "abacus": "abacus-ai-dark", "zai": "zai-dark",
    "synthetic": "synthetic", "warp": "warp", "codebuff": "codebuff",
    "lmstudio": "lmstudio",
}


def rasterize(svg_path):
    """SVG -> ICON_PX square RGBA, aspect-preserved, centered, transparent."""
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        png = tmp.name
    try:
        # -w only: rsvg scales height proportionally (aspect preserved).
        subprocess.run(
            ["rsvg-convert", "-w", str(ICON_PX * 4),
             "--background-color", "none", svg_path, "-o", png],
            check=True, capture_output=True)
        im = Image.open(png).convert("RGBA")
    finally:
        os.unlink(png)
    im.thumbnail((ICON_PX, ICON_PX), Image.LANCZOS)
    canvas = Image.new("RGBA", (ICON_PX, ICON_PX), (0, 0, 0, 0))
    canvas.paste(im, ((ICON_PX - im.width) // 2,
                      (ICON_PX - im.height) // 2))
    return canvas


def main():
    if not os.path.isdir(SVG_DIR):
        sys.exit(f"missing {SVG_DIR}")
    # Generate one A8 map per unique svg; ids reference them.
    svgs = sorted(set(ID_TO_SVG.values()))
    maps = {}        # svg basename -> list[int] (ICON_PX*ICON_PX alpha bytes)
    for base in svgs:
        path = os.path.join(SVG_DIR, base + ".svg")
        if not os.path.isfile(path):
            print(f"skip {base}: no svg", file=sys.stderr)
            continue
        rgba = rasterize(path)
        alpha = list(rgba.split()[-1].tobytes())   # row-major, 1 byte/px
        if max(alpha) < 8:
            print(f"skip {base}: rasterized blank", file=sys.stderr)
            continue
        maps[base] = alpha

    sym = lambda b: "ic_" + b.replace("-", "_")
    n = ICON_PX * ICON_PX
    c = ['// AUTO-GENERATED by scripts/gen-provider-icons.py — do not edit.',
         '// Source SVGs: scripts/assets/codexbar-logos/ (from CodexBar repo).',
         '#include "provider_icons.h"', '#include "lvgl.h"', '']
    for base in sorted(maps):
        data = maps[base]
        rows = []
        for r in range(ICON_PX):
            row = data[r * ICON_PX:(r + 1) * ICON_PX]
            rows.append("    " + ",".join(str(v) for v in row) + ",")
        c.append(f"static const uint8_t {sym(base)}_map[{n}] = {{")
        c.extend(rows)
        c.append("};")
        c.append(f"static const lv_image_dsc_t {sym(base)} = {{")
        c.append("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,")
        c.append("                .cf = LV_COLOR_FORMAT_A8,")
        c.append(f"                .w = {ICON_PX}, .h = {ICON_PX},"
                 f" .stride = {ICON_PX} }},")
        c.append(f"    .data_size = {n}, .data = {sym(base)}_map,")
        c.append("};")
        c.append("")
    c.append("const lv_image_dsc_t *provider_icon(const char *id)")
    c.append("{")
    c.append("    if (!id) return NULL;")
    c.append("    static const struct { const char *id;"
             " const lv_image_dsc_t *ic; } M[] = {")
    for pid in sorted(ID_TO_SVG):
        base = ID_TO_SVG[pid]
        if base in maps:
            c.append(f'        {{ "{pid}", &{sym(base)} }},')
    c.append("    };")
    c.append("    for (unsigned i = 0; i < sizeof M / sizeof *M; i++)")
    c.append("        if (strcmp(id, M[i].id) == 0) return M[i].ic;")
    c.append("    return NULL;")
    c.append("}")
    c.append("")
    with open(OUT_C, "w") as f:
        f.write("\n".join(c))
    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by scripts/gen-provider-icons.py.\n"
                "#pragma once\n#include \"lvgl.h\"\n#include <string.h>\n\n"
                "// A8 silhouette of the provider's CodexBar logo, or NULL.\n"
                "// Tint via the lv_image's image_recolor style.\n"
                "const lv_image_dsc_t *provider_icon(const char *id);\n")
    print(f"wrote {len(maps)} icons -> {os.path.relpath(OUT_C, HERE+'/..')}")


if __name__ == "__main__":
    main()
