#!/usr/bin/env python3
# gen-provider-icons.py — rasterize the vendored CodexBar provider logo SVGs
# (scripts/assets/codexbar-logos/, sourced from github.com/steipete/CodexBar
# docs/logos/) into small LVGL images and emit
# firmware/main/provider_icons.{c,h}.
#
# Most SVGs become **A8** (one alpha byte per pixel, shape coverage only, no
# color). The firmware tints these via the LVGL image_recolor style.
# SVGs listed in FULL_COLOR_SVGS are rendered as **ARGB8888** (full RGBA
# with the SVG's own colors) and the firmware skips recolor for those.
#
# Deps: rsvg-convert (brew install librsvg) + Pillow. Re-run after changing
# the vendored SVGs or ICON_PX; the generated .c is committed (build input,
# like the LVGL fonts).
#
#   python3 scripts/gen-provider-icons.py
import os, subprocess, sys, tempfile
from PIL import Image

ICON_PX = 32
HERE = os.path.dirname(os.path.abspath(__file__))
SVG_DIR = os.path.join(HERE, "assets", "codexbar-logos")
OUT_C = os.path.join(HERE, "..", "firmware", "main", "provider_icons.c")
OUT_H = os.path.join(HERE, "..", "firmware", "main", "provider_icons.h")

# SVG basenames whose native colors should be preserved (ARGB8888).
# Everything else is rendered as A8 (silhouette, tinted by firmware).
FULL_COLOR_SVGS = {"lmstudio"}

# provider id (UsageProvider raw value == payload `id`) -> svg basename.
# Several ids legitimately share one logo.
ID_TO_SVG = {
    "claude": "claude", "codex": "codex", "openai": "codex", "pi": "pi",
    "cursor": "cursor", "openrouter": "openrouter",
    "opencode": "opencode", "opencodego": "opencode",
    "ollama": "ollama", "gemini": "gemini", "copilot": "copilot",
    "alibaba": "alibaba", "amp": "amp", "antigravity": "antigravity",
    "augment": "augment", "deepseek": "deepseek", "elevenlabs": "elevenlabs",
    "factory": "droid", "jetbrains": "jetbrains-ai", "kilo": "kilo",
    "kimi": "kimi", "kimik2": "kimi-k2", "kiro": "kiro",
    "minimax": "minimax", "mistral": "mistral", "perplexity": "perplexity",
    "vertexai": "vertex-ai", "abacus": "abacus-ai-dark", "zai": "zai-dark",
    "synthetic": "synthetic", "warp": "warp", "codebuff": "codebuff",
    "lmstudio": "lmstudio",
}


def rasterize(svg_path):
    """SVG -> ICON_PX square RGBA, aspect-preserved, centered, transparent."""
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        png = tmp.name
    try:
        # -w only: rsvg scales height proportionally (aspect preserved).
        subprocess.run(
            ["rsvg-convert", "-w", str(ICON_PX * 4),
             "--background-color", "none", svg_path, "-o", png],
            check=True, capture_output=True)
        im = Image.open(png).convert("RGBA")
    finally:
        os.unlink(png)
    im.thumbnail((ICON_PX, ICON_PX), Image.LANCZOS)
    canvas = Image.new("RGBA", (ICON_PX, ICON_PX), (0, 0, 0, 0))
    canvas.paste(im, ((ICON_PX - im.width) // 2,
                      (ICON_PX - im.height) // 2))
    return canvas


def rgba_to_argb8888(rgba):
    """RGBA PIL Image -> flat list of ARGB8888 bytes (B, G, R, A per LVGL).

    LVGL's lv_color32_t is BGRA in memory on little-endian (ESP32).
    Returns one contiguous list of bytes for the whole ICON_PX^2 image.
    """
    pixels = list(rgba.getdata())
    out = []
    for r, g, b, a in pixels:
        out.extend([b, g, r, a])  # LVGL lv_color32_t: blue, green, red, alpha
    return out


def main():
    if not os.path.isdir(SVG_DIR):
        sys.exit(f"missing {SVG_DIR}")
    # Generate one map per unique svg; ids reference them.
    svgs = sorted(set(ID_TO_SVG.values()))
    maps = {}        # svg basename -> tuple(list[int], str)
                      #   (data bytes, color_format_string)
    for base in svgs:
        path = os.path.join(SVG_DIR, base + ".svg")
        if not os.path.isfile(path):
            print(f"skip {base}: no svg", file=sys.stderr)
            continue
        rgba = rasterize(path)
        if base in FULL_COLOR_SVGS:
            data = rgba_to_argb8888(rgba)
            cf = "LV_COLOR_FORMAT_ARGB8888"
        else:
            alpha = list(rgba.split()[-1].tobytes())  # row-major, 1 byte/px
            if max(alpha) < 8:
                print(f"skip {base}: rasterized blank", file=sys.stderr)
                continue
            data = alpha
            cf = "LV_COLOR_FORMAT_A8"
        maps[base] = (data, cf)

    sym = lambda b: "ic_" + b.replace("-", "_")
    n_a8 = ICON_PX * ICON_PX
    n_argb = n_a8 * 4
    c = ['// AUTO-GENERATED by scripts/gen-provider-icons.py — do not edit.',
         '// Source SVGs: scripts/assets/codexbar-logos/ (from CodexBar repo).',
         '#include "provider_icons.h"', '#include "lvgl.h"', '']
    for base in sorted(maps):
        data, cf = maps[base]
        is_full = base in FULL_COLOR_SVGS
        n = n_argb if is_full else n_a8
        stride = ICON_PX * 4 if is_full else ICON_PX
        rows = []
        srow = stride
        for r in range(ICON_PX):
            row = data[r * srow:(r + 1) * srow]
            rows.append("    " + ",".join(str(v) for v in row) + ",")
        c.append(f"static const uint8_t {sym(base)}_map[{n}] = {{")
        c.extend(rows)
        c.append("};")
        c.append(f"static const lv_image_dsc_t {sym(base)} = {{")
        c.append("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,")
        c.append(f"                .cf = {cf},")
        c.append(f"                .w = {ICON_PX}, .h = {ICON_PX},"
                 f" .stride = {stride} }},")
        c.append(f"    .data_size = {n}, .data = {sym(base)}_map,")
        c.append("};")
        c.append("")
    c.append("const lv_image_dsc_t *provider_icon(const char *id)")
    c.append("{")
    c.append("    if (!id) return NULL;")
    c.append("    static const struct { const char *id;"
             " const lv_image_dsc_t *ic; } M[] = {")
    for pid in sorted(ID_TO_SVG):
        base = ID_TO_SVG[pid]
        if base in maps:
            c.append(f'        {{ "{pid}", &{sym(base)} }},')
    c.append("    };")
    c.append("    for (unsigned i = 0; i < sizeof M / sizeof *M; i++)")
    c.append("        if (strcmp(id, M[i].id) == 0) return M[i].ic;")
    c.append("    return NULL;")
    c.append("}")
    c.append("")
    c.append("bool provider_icon_is_full_color(const char *id)")
    c.append("{")
    c.append("    if (!id) return false;")
    c.append("    static const char *F[] = {")
    for pid in sorted(ID_TO_SVG):
        base = ID_TO_SVG[pid]
        if base in FULL_COLOR_SVGS and base in maps:
            c.append(f'        "{pid}",')
    c.append("    };")
    c.append("    for (unsigned i = 0; i < sizeof F / sizeof *F; i++)")
    c.append("        if (strcmp(id, F[i]) == 0) return true;")
    c.append("    return false;")
    c.append("}")
    c.append("")
    with open(OUT_C, "w") as f:
        f.write("\n".join(c))
    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by scripts/gen-provider-icons.py.\n"
                "#pragma once\n#include \"lvgl.h\"\n#include <stdbool.h>\n#include <string.h>\n\n"
                "// A8 silhouette or ARGB8888 full-color image, or NULL.\n"
                "// A8 icons must be tinted via lv_image's image_recolor style;\n"
                "// ARGB8888 icons carry their own colors (check is_full_color).\n"
                "const lv_image_dsc_t *provider_icon(const char *id);\n"
                "\n"
                "// Returns true if the icon for `id` is ARGB8888 (full color).\n"
                "// When true, do NOT apply image_recolor to the icon.\n"
                "bool provider_icon_is_full_color(const char *id);\n")
    print(f"wrote {len(maps)} icons -> {os.path.relpath(OUT_C, HERE+'/..')}")


if __name__ == "__main__":
    main()
